language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -s tests
  - sonar-scanner

addons:
  sonarcloud:
    organization: "ilermak"
    token:
      secure: $SONAR_TOKEN
