name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Run pylint
      run: |
        pylint calculator.py

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=.
          -Dsonar.tests=tests
          -Dsonar.test.inclusions=tests/**/*.py
          -Dsonar.python.pylint.reportPaths=pylint-report.out
